begin;

do $$
begin
  create type public.user_role as enum ('employee', 'admin');
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.profiles (
  id uuid primary key references neon_auth."user"(id) on delete restrict,
  legacy_user_id bigint unique,
  username text not null unique,
  email text not null unique,
  legacy_email text,
  first_name text not null default '',
  last_name text not null default '',
  role public.user_role not null default 'employee',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.time_entries (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  user_id uuid references public.profiles(id) on delete restrict,
  legacy_user_id bigint,
  work_date date not null,
  sequence smallint not null default 1 check (sequence > 0),
  start_time timestamptz not null default now(),
  end_time timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint time_entries_user_reference check (
    user_id is not null or legacy_user_id is not null
  )
);

create unique index if not exists time_entries_user_workday_sequence_key
  on public.time_entries (user_id, work_date, sequence);
create index if not exists profiles_active_idx
  on public.profiles (is_active);
create index if not exists time_entries_user_date_idx
  on public.time_entries (user_id, work_date desc);
create index if not exists time_entries_work_date_idx
  on public.time_entries (work_date desc);
create index if not exists time_entries_legacy_user_idx
  on public.time_entries (legacy_user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists time_entries_set_updated_at on public.time_entries;
create trigger time_entries_set_updated_at
before update on public.time_entries
for each row execute function public.set_updated_at();

revoke all on public.profiles from public;
revoke all on public.time_entries from public;

commit;
